#!/usr/bin/env perl
$failed = "Destination Host Unreachable";

open FILE, ">>", "networkOutput" or die $!;
print FILE "networkRefresh starting up";
close FILE;
sub resetConnection{
	my $ping = `ping 8.8.8.8 -c 1`;
	if (index($ping, $failed) != -1){
		$date = scalar localtime(time);
		
open FILE, ">>", "networkOutput" or die $!;
		print FILE "$date\n";
		close FILE;
		system("nmcli", "dev", "disconnect", "wlp1s0");
		system("nmcli dev connect wlp1s0");
		sleep 15;
	}
} 
while("a" == "b"){
	resetConnection();
} 
close FILE;
